
$(document).ready(function(){
			  $("#attack").click(function(){
				$("#menus").hide();
				$("#menu1").show();
				$("#menu2").hide();
				$("#menu3").hide();
			  });
			  $("#chagepokemon").click(function(){
				$("#menus").hide();
				$("#menu2").show();
				$("#menu1").hide();
				$("#menu3").hide();
			  });
			  $("#bag").click(function(){
				$("#menus").hide();
				$("#menu3").show();
				$("#menu1").hide();
				$("#menu2").hide();
			  });
			  $("#back").click(function(){
				$("#menus").show();
				$("#menu1").hide();
				$("#menu2").hide();
				$("#menu3").hide();
			  });
			  $("#back2").click(function(){
				$("#menus").show();
				$("#menu1").hide();
				$("#menu2").hide();
				$("#menu3").hide();
			  });
			   $("#back3").click(function(){
				$("#menus").show();
				$("#menu1").hide();
				$("#menu2").hide();
				$("#menu3").hide();
				$("#potions_screen").hide();
				$("#potion_screen").hide();
				$("#ball_screen").hide();
			  });
			});