
$(document).ready(function(){
			  $("#attack2").click(function(){
				$("#menus2").hide();
				$("#menu12").show();
				$("#menu22").hide();
				$("#menu32").hide();
			  });
			  $("#chagepokemon2").click(function(){
				$("#menus2").hide();
				$("#menu22").show();
				$("#menu12").hide();
				$("#menu32").hide();
			  });
			  $("#bag2").click(function(){
				$("#menus2").hide();
				$("#menu32").show();
				$("#menu12").hide();
				$("#menu22").hide();
			  });
			  $("#back2").click(function(){
				$("#menus2").show();
				$("#menu12").hide();
				$("#menu22").hide();
				$("#menu32").hide();
			  });
			  $("#back22").click(function(){
				$("#menus2").show();
				$("#menu12").hide();
				$("#menu22").hide();
				$("#menu32").hide();
			  });
			   $("#back32").click(function(){
				$("#menus2").show();
				$("#menu12").hide();
				$("#menu22").hide();
				$("#menu32").hide();
				$("#potions_screen").hide();
				$("#potion_screen").hide();
				$("#ball_screen").hide();
			  });
			});