#!/usr/bin/env node
/**
 * Copies the Egret client out of the release and patches it for a WebView.
 *
 *   CLIENT_DIR=/path/to/XJLserver/client/Pokemon \
 *   SERVER_URL=http://your-server:8000 \
 *   npm run prepare:client
 *
 * The client is never committed to this repository — it is 189 MB of the
 * original game's assets. This script is how a checkout turns into a buildable
 * app on a machine that has the release.
 *
 * Three things are patched:
 *
 *  1. The server address. `Auth.$serverUrl` is baked into the minified bundle
 *     as the original operator's host, but `index.html` reloads it after the
 *     scripts load — the release even left the assignment there, commented
 *     out. That comment is the documented hook, so it is what gets replaced.
 *  2. The viewport, for notches and to stop the WebView zooming the canvas.
 *  3. A guard against the client redirecting itself back to the operator's
 *     domain when it does not recognise the platform it is running on.
 */
import { cp, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const APP_ROOT = path.resolve(import.meta.dirname, '..');
const WWW = path.join(APP_ROOT, 'www');

const CLIENT_DIR = process.env.CLIENT_DIR ?? process.argv[2] ?? '';
const SERVER_URL = (process.env.SERVER_URL ?? '').replace(/\/+$/, '');

function fail(message) {
  console.error(`[prepare] ${message}`);
  process.exit(1);
}

/** The comment the release left behind, used as the injection point. */
const HOOK = '//Auth.$serverUrl = "http://pokemon.qcymw.com/";';

async function main() {
  if (CLIENT_DIR === '') {
    fail('Set CLIENT_DIR to the extracted XJLserver/client/Pokemon directory.');
  }
  if (SERVER_URL === '') {
    fail('Set SERVER_URL to your game server, e.g. http://10.0.0.5:8000');
  }

  const indexPath = path.join(CLIENT_DIR, 'index.html');
  try {
    await stat(indexPath);
  } catch {
    fail(`No index.html under ${CLIENT_DIR} — is that the client directory?`);
  }

  console.log(`[prepare] copying client from ${CLIENT_DIR}`);
  await rm(WWW, { recursive: true, force: true });
  await mkdir(WWW, { recursive: true });
  await cp(CLIENT_DIR, WWW, { recursive: true });

  const original = await readFile(indexPath, 'utf8');
  const patched = patchIndex(original);
  await writeFile(path.join(WWW, 'index.html'), patched, 'utf8');

  await writeFile(
    path.join(WWW, 'server-config.js'),
    `// Generated by scripts/prepare-client.mjs — do not edit by hand.\n` +
      `window.POKEH5_SERVER_URL = ${JSON.stringify(SERVER_URL)};\n`,
    'utf8',
  );

  console.log(`[prepare] server URL set to ${SERVER_URL}`);
  console.log(`[prepare] wrote ${WWW}`);
}

function patchIndex(html) {
  let out = html;

  // 1. Server address.
  if (!out.includes(HOOK)) {
    fail(
      'Could not find the Auth.$serverUrl hook in index.html. The client build ' +
        'differs from the one this script was written against — patch it by hand.',
    );
  }
  out = out.replace(
    HOOK,
    'Auth.$serverUrl = window.POKEH5_SERVER_URL || Auth.$serverUrl;',
  );

  // The config has to exist before the bundle's callback runs, so it is loaded
  // synchronously ahead of everything else.
  out = out.replace('</head>', '  <script src="server-config.js"></script>\n</head>');

  // 2. Viewport. The stock tag is a fixed 360px wide with no notch handling.
  out = out.replace(
    /<meta name="viewport"[\s\S]*?\/>/,
    '<meta name="viewport" content="width=360,user-scalable=no,viewport-fit=cover"/>',
  );

  // 3. A WebView is not a browser the client recognises, and on an unknown
  //    platform it redirects to `clientURL` — the operator's own domain. Being
  //    explicit about the platform keeps the app inside itself.
  out = out.replace(
    'game.isMobile = true;',
    'game.isMobile = true;\n                Auth.$platformType = 0;',
  );

  return out;
}

main().catch((error) => fail(error.message));
